version: "3.8"
services:
  db:
    image: postgres:16-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - "5432"
    restart: always
  server:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    expose:
      - 3000
    depends_on:
      - db
    restart: always
